Filminurk/Models/FavouriteLists/FavouriteListIndexImageViewModel.cs
namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListIndexImageViewModel
    {
        public Guid ImageID { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageData { get; set; }
        public string Image {  get; set; }
        public Guid? ListID { get; set; }
    }
}

Filminurk/Models/FavouriteLists/FavouriteListsIndexViewModel.cs
using Filminurk.Core.Domain;
using Filminurk.Models.Movies;
using System.ComponentModel.DataAnnotations;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListsIndexViewModel
    {
        
        public Guid? FavouriteListID { get; set; }
        public string ListBelongsToUser { get; set; }
        public bool IsMoviesOrActor { get; set; }
        public string ListName { get; set; }
        public string? ListDescription { get; set; }
        public bool? IsPrivate { get; set; }
        //public List<Movie>? ListOfMovies { get; set; }
        //public List<Actor>? ListOfActors { get; set; }


        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool? IsReported { get; set; } = false;
        //imagemodel for index
        public List<FavouriteListIndexImageViewModel> Image { get; set; }=new List<FavouriteListIndexImageViewModel>();
    }
}

Filminurk/Models/FavouriteLists/FavouriteListsUserCreateViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteLists
{
    public class FavouriteListsUserCreateViewModel
    {
        public Guid? FavouriteListID { get; set; }
        public string ListBelongsToUser { get; set; }
        public bool IsMoviesOrActor { get; set; }
        public string ListName { get; set; }
        public string ListDescription { get; set; }
        public bool IsPrivate { get; set; }
        public List<Movie> ListOfMovies { get; set; }
        //public List<Actor>? ListOfActors { get; set; }


        public DateTime? ListModifiedAt { get; set; }
        public DateTime? ListCreatedAt { get; set; }
        public DateTime? ListDeletedAt { get; set; }
        public bool? IsReported { get; set; } = false;
        //imagemodel for index
        public List<FavouriteListIndexImageViewModel> Image { get; set; } = new List<FavouriteListIndexImageViewModel>();
    }
}

Filminurk/Controllers/FavouriteListsController.cs
using Filminurk.Core.Domain;
using Filminurk.Core.Dto;
using Filminurk.Core.ServiceInterface1;
using Filminurk.Data;
using Filminurk.Models.FavouriteLists;
using Filminurk.Models.Movies;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class FavouriteListsController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly IFavouriteListsServices _favouriteListsServices;
        //fileservice add later
        public FavouriteListsController(FilminurkTARpe24Context context, IFavouriteListsServices favouriteListsServices)
        {
            _context = context;
            _favouriteListsServices = favouriteListsServices;
        }
        public IActionResult Index()
        {
            var resultingLists = _context.FavouriteLists
                .OrderByDescending(y => y.ListCreatedAt)
                .Select(x => new FavouriteListsIndexViewModel
                {
                    FavouriteListID = x.FavouriteListID,
                    ListBelongsToUser = x.ListBelongsToUser,
                    ListCreatedAt = x.ListCreatedAt,
                    ListDescription = x.ListDescription,
                    ListName = x.ListName,
                    IsMoviesOrActor = x.IsMoviesOrActor,
                    Image = (List<FavouriteListIndexImageViewModel>)_context.FilesToDatabase
                    .Where(ml => ml.ListID == x.FavouriteListID)
                    .Select(li => new FavouriteListIndexImageViewModel()
                    {
                        ImageID = li.ImageID,
                        ListID = li.ListID,
                        ImageData = li.ImageData,
                        ImageTitle = li.ImageTitle,
                        Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(li.ImageData)),
                    })
                });
            return View(resultingLists);
        }
        [HttpGet]
        public IActionResult Create()
        {
            //todo: identify user type. return diffrent views for admin and user
            var movies=_context.Movies
                .OrderBy(m => m.Title)
                .Select(m=> new MoviesIndexViewModel
                {
                    ID = m.ID,
                    Title = m.Title,
                    FirstPublished = m.FirstPublished,
                    Awards = m.Awards,

                })
                .ToList();
            ViewData["allmovies"] = movies;
            ViewData["userHasSelected"]=new List<string>();
            //for normal  user
            FavouriteListsUserCreateViewModel vm = new();
            return View("UserCreate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> UserCreate(FavouriteListsUserCreateViewModel vm, List<string> userHasSelected,
            List<MoviesIndexViewModel> movies)
        {
            List<Guid> tempParse = new();
            foreach (var stringID in userHasSelected) 
            { 
              tempParse.Add(Guid.Parse(stringID));
            }
            var newListDto = new FavouriteListDTO() { };
            newListDto.ListName=vm.ListName;
            newListDto.ListDescription=vm.ListDescription;
            newListDto.IsMoviesOrActor=vm.IsMoviesOrActor;
            newListDto.IsPrivate=vm.IsPrivate;
            newListDto.ListCreatedAt= (DateTime)vm.ListCreatedAt;
            newListDto.ListBelongsToUser = "00000000-0000-000-000-000000000001";
            newListDto.ListModifiedAt=DateTime.UtcNow;
            newListDto.ListDeletedAt= vm.ListDeletedAt;
            newListDto.ListOfMovies= vm.ListOfMovies;

            var listofmoviestoadd = new List<Movie>();
            foreach (var movieId in tempParse) 
            {
                var thismovie = _context.Movies.Where(tm => tm.ID == movieId).ToList().Take(1);
                newListDto.ListOfMovies.Add((Movie)thismovie);
            }
            newListDto.ListOfMovies = listofmoviestoadd;
            //List<Guid>convertedIDS = new List<Guid>();
            //if (newListDto.ListOfMovies !=null)
            //{
            //    convertedIDS= MovieToId(newListDto.ListOfMovies);
            //}
            var newList = await _favouriteListsServices.Create(newListDto  /*convertedIDS*/);
            if (newList != null) 
            {
                return BadRequest();
            }
            return RedirectToAction("Index", vm);
        }

        private List<Guid> MovieToId(List<Movie> listOfMovies)
        {
            var results= new List<Guid>();
            foreach (var movie in listOfMovies) 
            { 
              results.Add(movie.ID);
            }
            return results;
        }
        public async Task<FavouriteList> Create(FavouriteList dto, List<Movie> selectedMovies)
        {
            FavouriteList newList = new();
            newList.FavouriteListID=Guid.NewGuid();
            newList.ListName=dto.ListName;
            newList.ListDescription=dto.ListDescription;
            newList.ListCreatedAt=dto.ListCreatedAt;
            newList.ListModifiedAt=dto.ListModifiedAt;
            newList.ListDeletedAt=dto.ListDeletedAt;
            //newList.ListOfMovies=selectedMovies;
            await _context.FavouriteLists.AddAsync(newList);
            await _context.SaveChangesAsync();

            //foreach (var movieid in selectedMovies) 
            //{
               // _context.FavouriteLists.Entry

            //}
            return newList;
        }
    }
}

Filminurk/Views/FavouriteLists/Index.cshtml
@model IEnumerable<Filminurk.Models.FavouriteLists.FavouriteListsIndexViewModel>

@{
	int rownumber = 1;
	int currentrow = 1;
	int currenttile = 1;
	int tilesInRow = 1;
}
<div>
	<a asp-action="Create" asp-controller="FavouriteLists" class="btn btn-primary">Tee uus lemmikute nimekiri</a>
	<a asp-action="Index" asp-controller="Home" class="btn btn-primary">Pealeht</a>
</div>
<div@*no class currently, no design*@>
	<form method="form">
		<table class="table">
			<thead>
				@if(Model.Any())
				{
					<tr>
						<th scope="col" colspan="2">
							<span>Kahjuks ei leidnud ühtegi lemmikute nimekirja</span>
						</th>
					</tr>
				}
				else
				{
					<tr>
						<th scope="col" colspan="2">
							<span>Sinu nimekirjad:</span>
						</th>
					</tr>
				}
			</thead>
			<tbody>
				@if (!Model.Any())
				{
					<table>
						<tr>
							<td colspan="2">Sorry, no list</td>
						</tr>
						<tr>
							<td><img width="128" src="~/lib/defaultassets/image/Nimetu.png"></td>
						</tr>
					</table>
				}
				else
				{
					@foreach(var list in Model)
					{
						<table>
							<tr>
								<td colspan="2">
									<a asp-action="ListDetailsListOwner" asp-controller="FavouriteLists" asp-route-id="@list.FavouriteListID">@list.ListName</a>
								</td>
							</tr>
							<tr>
								<td>
									@foreach(var image in list.Image)
									{
										<partial name="_ImageIndex" model="image" />
									}
								</td>
								<td>@list.ListDescription</td>
							</tr>
						</table>

					}
					rownumber++;
				}
			</tbody>
		</table>
	</form>
</div>

Filminurk/Views/FavouriteLists/UserCreate.cshtml
@model Filminurk.Models.FavouriteLists.FavouriteListsUserCreateViewModel
@*checks for editing or creating*@
@{
	var allMoviesTickBoxes = ViewData["allmovies"] as List<Filminurk.Models.Movies.MoviesIndexViewModel>;
	List<string> userHasSelected = ViewBag.userHasSelected;
	List<string> previousSelected = userHasSelected;
}
<h1>Tee uus nimekiri</h1>
<div>
	<form method="post" entype="multipart/form-data">
		<input asp-for="FavouriteListID" type="hidden" />
		<input asp-for="ListModifiedAt" type="hidden" />
		<input asp-for="ListCreatedAt" type="hidden" />
		<input asp-for="ListDeletedAt" type="hidden" />
		<input asp-for="IsReported" type="hidden" />
		<input asp-for="ListBelongsToUser" type="hidden" />

		<div class="form-group-row">
			<label asp-for="ListName" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="ListName" class="form-control" />
			</div>
		</div>
		<div class="form-group-row">
			<label asp-for="ListDescription" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="ListDescription" class="form-control" />
			</div>
		</div>
		<div class="form-group-row">
			<label asp-for="IsPrivate" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input type="checkbox" asp-for="IsPrivate" class="form-control" />
			</div>
		</div>
		@if (allMoviesTickBoxes == null)
		{
			@:Filme andmebaasis ei ole
		}
		else
		{
			@foreach (var movie in ViewBag.allmovies)
			{
				<tr>
					<td>@movie.Title</td>
					<td>@movie.FirstPublished</td>
					<td>@movie.Awards</td>
					<td>
						@if (movie.ID.HasValue)
						{
							<input type="checkbox" name="userHasSelected" value="@movie.ID" id="checkbox-@movie.ID" 
							@if(userHasSelected.Contains(movie.ID.ToString()))
							{
								@:checked
							}
							/>
						}
						else
						{
							<tr>
						       <input type="checkbox" name="userHasSelected" value="@movie.ID" id="checkbox-@movie.ID" />
							</tr>
							
						}
				   </td>
			   </tr>
			}
			
		}
		<input 
			asp-action="UserCreate"
			asp-controller="=FavouriteLists"
			type="submit"
			class="btn btn-primary"
			value="Tee Nimekiri"
		/>

		
	</form>
</div>

Filminurk/Views/FavouriteLists/_ImageIndex.cshtml
@model Filminurk.Models.FavouriteLists.FavouriteListIndexImageViewModel
<div>
	@if(!Model.Image.Any())
	{
		<p>Cannot find images</p>
	}
</div>
@if(Model.ImageTitle=="Poster")
{
	<img class="card-img-top" src="@Model.Image" asp-append-version="true"/>
}
else
{
	<img width="128" src="~/lib/defaultassets/image/Nimetu.png">
}