Filminurk/Models/Movies/ImageViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Filminurk.Models.Movies
{
    public class ImageViewModel
    {
        
        public Guid ImageID { get; set; }
        public string? FilePath { get; set; }
        public Guid? MovieID { get; set; }
        public bool? IsPoster { get; set; }//määrab ära kas poster 
    }
}

Filminurk/Models/Movies/MovieDeleteViewModel.cs
namespace Filminurk.Models.Movies
{
    public class MovieDeleteViewModel
    {
        public Guid? ID { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public DateOnly? FirstPublished { get; set; }
        public string? Director { get; set; }
        public List<string>? Actors { get; set; }
        public decimal? CurrentRating { get; set; }


        //enda valitud andmed

        public int? Profit { get; set; }
        public string? Awards { get; set; }
        public string? AwardsDescription { get; set; }

        //andmebaasi jaoks vajalikud
        public DateTime? EntryCreatedAt { get; set; }
        public DateTime? EntryModifiedAt { get; set; }
    }
}

Filminurk/Models/Movies/MovieDetailsViewModel.cs
namespace Filminurk.Models.Movies
{
    public class MovieDetailsViewModel
    {
        public Guid? ID { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public DateOnly? FirstPublished { get; set; }
        public string? Director { get; set; }
        public List<string>? Actors { get; set; }
        public decimal? CurrentRating { get; set; }


        //enda valitud andmed

        public int? Profit { get; set; }
        public string? Awards { get; set; }
        public string? AwardsDescription { get; set; }

        //andmebaasi jaoks vajalikud
        public DateTime? EntryCreatedAt { get; set; }
        public DateTime? EntryModifiedAt { get; set; }
    }
}

Filminurk/Models/Movies/MoviesCreateUpdateViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.Movies
{
    public class MoviesCreateUpdateViewModel
    {
        public Guid? ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateOnly FirstPublished { get; set; }
        public string Director { get; set; }
        public List<Actor>? Actors{ get; set; }
        public decimal? CurrentRating { get; set; }
        /* kaasasolevate piltide andmeomadused */
        public List<IFormFile>? Files{ get; set; }
        public List<ImageViewModel>? Images{ get; set; } = new List<ImageViewModel>();


        //enda valitud andmed

        public int? Profit { get; set; }
        public string? Awards { get; set; }
        public string? AwardsDescription { get; set; }

        //andmebaasi jaoks vajalikud
        public DateTime? EntryCreatedAt { get; set; }
        public DateTime? EntryModifiedAt { get; set; }
    }
}

Filminurk/Models/Movies/MoviesCreateViewModel.cs
namespace Filminurk.Models.Movies
{
    public class MoviesCreateViewModel
    {
        public Guid ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateOnly FirstPublished { get; set; }
        public string Director { get; set; }
        public List<string>? Actors{ get; set; }
        public decimal? CurrentRating { get; set; }


        //enda valitud andmed

        public int? Profit { get; set; }
        public string? Awards { get; set; }
        public string? AwardsDescription { get; set; }

        //andmebaasi jaoks vajalikud
        public DateTime? EntryCreatedAt { get; set; }
        public DateTime? EntryModifiedAt { get; set; }
    }
}

Filminurk/Models/Movies/MoviesDeleteViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.Movies
{
    public class MoviesDeleteViewModel
    {
        public Guid? ID { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public DateOnly? FirstPublished { get; set; }
        public string? Director { get; set; }
        public List<Actor>? Actors { get; set; }
        public decimal? CurrentRating { get; set; }
        /* kaasasolevate piltide andmeomadused */
        public List<ImageViewModel> Images { get; set; } = new List<ImageViewModel>();

        //enda valitud andmed

        public int? Profit { get; set; }
        public string? Awards { get; set; }
        public string? AwardsDescription { get; set; }

        //andmebaasi jaoks vajalikud
        public DateTime? EntryCreatedAt { get; set; }
        public DateTime? EntryModifiedAt { get; set; }
    }
}

Filminurk/Models/Movies/MoviesDetailsViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.Movies
{
    public class MoviesDetailsViewModel
    {
        public Guid? ID { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public DateOnly? FirstPublished { get; set; }
        public string? Director { get; set; }
        public List<Actor>? Actors { get; set; }
        public decimal? CurrentRating { get; set; }
        /* kaasasolevate piltide andmeomadused */
        public List<ImageViewModel> Images { get; set; } = new List<ImageViewModel>();

        //enda valitud andmed

        public int? Profit { get; set; }
        public string? Awards { get; set; }
        public string? AwardsDescription { get; set; }

        //andmebaasi jaoks vajalikud
        public DateTime? EntryCreatedAt { get; set; }
        public DateTime? EntryModifiedAt { get; set; }
    }
}

Filminurk/Models/Movies/MoviesIndexViewModel.cs
namespace Filminurk.Models.Movies
{
    public class MoviesIndexViewModel
    {
        public Guid ID { get; set; }
        public string Title { get; set; }
        public DateOnly FirstPublished { get; set; }
        public double? CurrentRating { get; set; }


        //enda valitud andmed

        public int? Profit { get; set; }
        public string? Awards { get; set; }
        public string? AwardsDescription { get; set; }
    }

}

Filminurk/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Filminurk.Models.Movies;
using Filminurk.Data;
using Filminurk.Core.Dto;
using Filminurk.Core.ServiceInterface1;
using Microsoft.EntityFrameworkCore;


namespace Filminurk.Controllers
{
    public class MoviesController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly IMovieServices _movieServices;
        private readonly IFilesServices _filesServices;
        public MoviesController(FilminurkTARpe24Context context, IMovieServices movieServices, IFilesServices filesServices)
        {
            _context = context;
            _movieServices = movieServices;
            _filesServices = filesServices;
        }

        public IActionResult Index()
        {
            var result = _context.Movies.Select(x => new MoviesIndexViewModel
            {
                ID=x.ID,
                Title=x.Title,
                FirstPublished=x.FirstPublished,
                CurrentRating=x.CurrentRating,
                Profit=x.Profit,
                Awards=x.Awards,
                AwardsDescription=x.AwardsDescription,
            });
            return View(result);
        }
        [HttpGet]
        public IActionResult Create() 
        {
            MoviesCreateUpdateViewModel result = new();
            return View("CreateUpdate", result);
        }
        [HttpPost]
        public async Task<IActionResult> Create(MoviesCreateUpdateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var dto = new MoviesDTO()
                {
                    ID = viewModel.ID,
                    Title = viewModel.Title,
                    Description = viewModel.Description,
                    FirstPublished = viewModel.FirstPublished,
                    Director = viewModel.Director,
                    Actors = viewModel.Actors,
                    CurrentRating = viewModel.CurrentRating,
                    Profit = viewModel.Profit,
                    Awards = viewModel.Awards,
                    AwardsDescription = viewModel.AwardsDescription,
                    EntryCreatedAt = viewModel.EntryCreatedAt,
                    EntryModifiedAt = viewModel.EntryModifiedAt,
                    Files = viewModel.Files,
                    FilesToApiDTOs=viewModel.Images
                      .Select(x=> new FileToApiDTO
                      {
                          ImageID = x.ImageID,
                          FilePath = x.FilePath,
                          MovieID = x.MovieID,
                          IsPoster = x.IsPoster,
                      }).ToArray()

                };
                var result = await _movieServices.Create(dto);
                if (result == null)
                {
                   
                    return NotFound();
                }
                if (!ModelState.IsValid)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));

            }
            return RedirectToAction(nameof(Index));

        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var movie=await _movieServices.DetailsAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            ImageViewModel[] images= await FilesFromDatabase(id);
            var vm = new MoviesDetailsViewModel();
            vm.ID = movie.ID;
            vm.Title = movie.Title;
            vm.Description = movie.Description;
            vm.FirstPublished = movie.FirstPublished;
            vm.Director = movie.Director;
            vm.Actors = movie.Actors;
            vm.CurrentRating = movie.CurrentRating;
            vm.Profit = movie.Profit;
            vm.Awards = movie.Awards;
            vm.AwardsDescription = movie.AwardsDescription;
            vm.Actors = movie.Actors;
            vm.EntryCreatedAt = movie.EntryCreatedAt;
            vm.EntryModifiedAt = movie.EntryModifiedAt;
            vm.Images.AddRange(images);
            return View(vm);
        }
        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var movie=await _movieServices.DetailsAsync(id);
            if (movie==null)
            {
                return NotFound();
            }

            var images = await _context.FilesToApi
                .Where(x => x.MovieID == id)
                .Select(y => new ImageViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageID = id,
                }).ToArrayAsync();        
            
            var vm = new MoviesCreateUpdateViewModel();
            vm.ID = movie.ID;
            vm.Title = movie.Title;
            vm.Description = movie.Description;
            vm.FirstPublished = movie.FirstPublished;
            vm.Director = movie.Director;
            vm.Actors = movie.Actors;
            vm.CurrentRating = movie.CurrentRating;
            vm.Profit = movie.Profit;
            vm.Awards = movie.Awards;
            vm.AwardsDescription = movie.AwardsDescription;
            vm.Actors = movie.Actors;
            vm.EntryCreatedAt = movie.EntryCreatedAt;
            vm.EntryModifiedAt = movie.EntryModifiedAt;
            vm.Images.AddRange(images);

            return View("CreateUpdate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(MoviesCreateUpdateViewModel vm)
        {
            var dto = new MoviesDTO()
            {
                ID = vm.ID,
                Title = vm.Title,
                Description = vm.Description,
                FirstPublished = vm.FirstPublished,
                Director = vm.Director,
                Actors = vm.Actors,
                CurrentRating = vm.CurrentRating,
                Profit = vm.Profit,
                Awards = vm.Awards,
                AwardsDescription = vm.AwardsDescription,
                EntryCreatedAt = vm.EntryCreatedAt,
                EntryModifiedAt = vm.EntryModifiedAt,
                Files = vm.Files,
                FilesToApiDTOs= vm.Images
                .Select(x=> new FileToApiDTO()
                 {
                     ImageID = x.ImageID,
                     MovieID = x.ImageID,
                     FilePath = x.FilePath,
                 }).ToArray()
            };
            var result=await _movieServices.Update(dto);
            if (result == null)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var movie=await _movieServices.DetailsAsync(id);
            if (movie != null)
            {
                return NotFound();
            }
            var images = await _context.FilesToApi
                .Where(x => x.MovieID == id)
                .Select(y => new ImageViewModel()
                {
                    FilePath = y.ExistingFilePath,
                    ImageID = y.ImageID,
                }).ToArrayAsync();

            var vm = new MoviesDeleteViewModel();
            vm.ID = movie.ID;
            vm.Title = movie.Title;
            vm.Description = movie.Description;
            vm.FirstPublished = movie.FirstPublished;
            vm.Director = movie.Director;
            vm.Actors = movie.Actors;
            vm.CurrentRating = movie.CurrentRating;
            vm.Profit = movie.Profit;
            vm.Awards = movie.Awards;
            vm.AwardsDescription = movie.AwardsDescription;
            vm.Actors= movie.Actors;
            vm.EntryCreatedAt = movie.EntryCreatedAt;
            vm.EntryModifiedAt = movie.EntryModifiedAt;
            vm.Images.AddRange(images);
              
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var movie = await _movieServices.Delete(id);
            if (movie != null)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }
        private async Task<ImageViewModel[]> FilesFromDatabase(Guid id)
        {
            return await _context.FilesToApi
                .Where(x => x.MovieID == id)
                .Select(y => new ImageViewModel
                {
                    ImageID = y.ImageID,
                    MovieID = y.MovieID,
                    IsPoster = y.IsPoster,
                    FilePath = y.ExistingFilePath
                }).ToArrayAsync();
        }

    }
}

Filminurk/Views/Movies/Create.cshtml
@model Filminurk.Models.Movies.MoviesCreateViewModel

<h1>Lisa Film</h1>
<div>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="ID" type="hidden" />
		<input asp-for="EntryCreatedAt" type="hidden" />
		<input asp-for="EntryModifiedAt" type="hidden" />

		<div class="form-group row">
			<label asp-for="Title" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10"> 
				<input asp-for="Title" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Description" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Description" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="FirstPublished" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="FirstPublished" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Director" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Director" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="CurrentRating" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="CurrentRating" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Profit" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Profit" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Awards" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Awards" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="AwardsDescription" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="AwardsDescription" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="EntryCreatedAt" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="EntryCreatedAt" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="EntryModifiedAt" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="EntryModifiedAt" class="form-control" />
			</div>
		</div>
		<div>
			<input asp-action="Create" asp-controller="Movies" type="submit" class="btn btn-primary" value="Create" />
		</div>
	</form>
</div>

Filminurk/Views/Movies/CreateUpdate.cshtml
@model Filminurk.Models.Movies.MoviesCreateUpdateViewModel


@if (Model.ID.HasValue)
{
	<h1>Muuda Film</h1>
}
else
{
	<h1>Lisa Film</h1>
}



<div>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="ID" type="hidden" />
		<input asp-for="EntryCreatedAt" type="hidden" />
		<input asp-for="EntryModifiedAt" type="hidden" />

		<div class="form-group row">
			<label asp-for="Title" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10"> 
				<input asp-for="Title" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Description" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Description" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="FirstPublished" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="FirstPublished" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Director" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Director" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="CurrentRating" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="CurrentRating" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Profit" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Profit" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Awards" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Awards" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="AwardsDescription" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="AwardsDescription" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="EntryCreatedAt" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="EntryCreatedAt" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="EntryModifiedAt" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="EntryModifiedAt" class="form-control" />
			</div>
		</div>
		<div class="form-group row">
			<label asp-for="Files" classs="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input class="form-control" asp-for="Files" multiple type="file" />
			</div>
		</div>
		@foreach(var images in Model.Images)
		{
			<partial name="_Images" model="images" />
			<input asp-action="removeImage" asp-controller="Movies" asp-route-ImageID="@images.ImageID" type="submit" 
			class="btn btn-success" value="Eemalda see pilt"/>
		}
		<div>
			@if (Model.ID.HasValue)
			{
				<input asp-action="Update" asp-controller="Movies" type="submit" class="btn btn-primary" value="Update" />
			}
			else
			{
				<input asp-action="Create" asp-controller="Movies" type="submit" class="btn btn-primary" value="Create" />
			}
			<a asp-action="Index" asp-controller="Movies" class="btn btn-sucess">Back</a>
		</div>
	</form>
</div>

Filminurk/Views/Movies/Delete.cshtml
@model Filminurk.Models.Movies.MoviesDeleteViewModel

<h1>Kustuta Film</h1>

<div>

	<h4>Film</h4>
	<hr />
	<dl class="row"></dl>
	 <div class="form-group-row">
		 <label asp-for="ID" class="col-sm-2" col-form-label""></label>
		 @Html.DisplayFor(model=>model.ID)
	</div>
	<dl class="row"></dl>
	<div class="form-group-row">
		<label asp-for="Title" class="col-sm-2" col-form-label""></label>
		@Html.DisplayFor(model => model.Title)
	</div>
	<dl class="row"></dl>
	<div class="form-group-row">
		<label asp-for="Description" class="col-sm-2" col-form-label""></label>
		@Html.DisplayFor(model => model.Description)
	</div>
	<dl class="row"></dl>
	<div class="form-group-row">
		<label asp-for="FirstPublished" class="col-sm-2" col-form-label""></label>
		@Html.DisplayFor(model => model.FirstPublished)
	</div>
	<dl class="row"></dl>
	<div class="form-group-row">
		<label asp-for="Director" class="col-sm-2" col-form-label""></label>
		@Html.DisplayFor(model => model.Director)
	</div>
	<dl class="row"></dl>
	<div class="form-group-row">
		<label asp-for="CurrentRating" class="col-sm-2" col-form-label""></label>
		@Html.DisplayFor(model => model.CurrentRating)
	</div>
	<dl class="row"></dl>
	<div class="form-group-row">
		<label asp-for="Profit" class="col-sm-2" col-form-label""></label>
		@Html.DisplayFor(model => model.Profit)
	</div>
	<dl class="row"></dl>
	<div class="form-group-row">
		<label asp-for="Awards" class="col-sm-2" col-form-label""></label>
		@Html.DisplayFor(model => model.Awards)
	</div>
	<hr />
	<form asp-action="DeleteConfirmation">
		<input type="hidden" asp-for="ID" />
		<input type="submit" value="Remove" class="btn btn danger"/>
		<a asp-action="Index" asp-controller="Movies" class="btn btn-success">Return to list</a>
	</form>
</div>

Filminurk/Views/Movies/Details.cshtml
@model Filminurk.Models.Movies.MoviesDetailsViewModel

<h1>Filmi info</h1>

<div>
	<h4>Filmi info</h4>
	<hr />
	<dl class="row">
		<div class="form-group row">
			<label asp-for="ID" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.ID)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Title" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.Title)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Description" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.Description)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="FirstPublished" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.FirstPublished)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Director" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.Director)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Actors" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.Actors)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CurrentRating" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.CurrentRating)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Profit" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.Profit)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Awards" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.Awards)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="AwardsDescription" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.AwardsDescription)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="EntryCreatedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.EntryCreatedAt)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="EntryModifiedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(Model => Model.EntryModifiedAt)
		</div>
	</dl>
	<dl>
		@foreach(var images in Model.Images)
		{
			<partial name="_Images" model="images" />
		}
	</dl>
	<hr />

	<a asp-action="Index" asp-controller="Movies" class="btn btn-danger">Back</a>
</div>

Filminurk/Views/Movies/Index.cshtml
@model IEnumerable<Filminurk.Models.Movies.MoviesIndexViewModel>

@{
	int rowNumber = 1;
}

<div>
	<a asp-action="Create" asp-controller="Movies" type="submit" class="btn btn-primary">Add Movie</a>
</div>
<div class="h1">
	Filmid
</div>
<form method="get">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Filmi pealkiri</th>
				<th scope="col">Väljalaskeaeg</th>
				<th scope="col">Hinnang</th>
				<th scope="col">Kasum</th>
				<th scope="col">Auhinnad</th>
				<th scope="col">Auhinna kirjeldus</th>
				<th scope="col">Tööriistad</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var movie in Model)
			{
				<tr>
					<td>@rowNumber</td>
					<td>@movie.Title</td>
					<td>@movie.FirstPublished</td>
					<td>@movie.CurrentRating</td>
					<td>@movie.Profit</td>
					<td>@movie.Awards</td>
					<td>@movie.AwardsDescription</td>
					<td> 
						<a asp-action="Delete" asp-controller="Movies" asp-route-id="@movie.ID" class="btn btn-outline-danger">Kustuta</a>
						<a asp-action="Update" asp-controller="Movies" asp-route-id="@movie.ID" class="btn btn-outline-danger">Uuenda</a>
						<a asp-action="Details" asp-controller="Movies" asp-route-id="@movie.ID" class="btn btn-outline-danger">Info</a>
					</td>
				</tr>
				rowNumber += 1;
			}
		</tbody>

	</table>
</form>

Filminurk/Views/Movies/_Images.cshtml
@model Filminurk.Models.Movies.ImageViewModel
@{
	var photoPaths = "~/multipleFileUpload/" + (Model.FilePath ?? "noimage.jpg");
}
<div class="form-group row col-sm-4 offset-2">
	<div>
		@Model.FilePath
	</div>
	<img class="card-image-top" src="@photoPaths" asp-append-version="true" />
</div>