Filminurk/Models/Actors/ActorsIndexViewModel.cs
using static Filminurk.Core.Domain.Actor;

namespace Filminurk.Models.Actors
{
    public class ActorsIndexViewModel
    {
        public Guid ActorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public List<string>? NickName { get; set; }
        public Guid PortraitID { get; set; }

        public int? Age { get; set; }
        public string? Gender { get; set; }
        public Child? Children { get; set; }
    }
}

Filminurk/Controllers/ActorsController.cs
using Filminurk.Core.ServiceInterface1;
using Filminurk.Data;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class ActorsController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly IMovieServices _movieServices;
        private readonly IFilesServices _filesServices;
        public ActorsController(FilminurkTARpe24Context context, IMovieServices movieServices, IFilesServices filesServices)
        {
            _context = context;
            _movieServices = movieServices;
            _filesServices = filesServices;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Filminurk/Views/Actors/Index.cshtml
@model IEnumerable<Filminurk.Models.Actors.ActorsIndexViewModel>

@{
	int rowNumber = 1;
}
<div>
	<a asp-action="Create" asp-controller="Actors" type="submit" class="btn btn-primary">Add Actor</a>
</div>
<div class="h1">
	Actors
</div>
<form method="get">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">FirstName</th>
				<th scope="col">LastName</th>
				<th scope="col">NickName</th>
				<th scope="col">PortraitID</th>
				<th scope="col">Age</th>
				<th scope="col">Gender</th>
				<th scope="col">Tööriistad</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var actor in Model)
			{
				<tr>
					<td>@rowNumber</td>
					<td>@actor.FirstName</td>
					<td>@actor.LastName</td>
					<td>@actor.NickName</td>
					<td>@actor.PortraitID</td>
					<td>@actor.Age</td>
					<td>@actor.Gender</td>
					
					<td>
						
					</td>
				</tr>
				rowNumber += 1;
			}
		</tbody>

	</table>
</form>