Filminurk/Models/UserComments/UserCommentsCreateViewModel.cs
namespace Filminurk.Models.UserComments
{
    public class UserCommentsCreateViewModel
    {
        public Guid CommentID { get; set; }
        public string CommentUserID { get; set; } = "00000000-0000-0000-000000000001";
        public string CommentBody { get; set; }
        public int? CommentScore { get; set; }
        public int? IsHelpful { get; set; }
        public int? IsHarmful { get; set; }
        public DateTime CommentCreatedAt { get; set; }
        public DateTime CommentModifiedAt { get; set; }
        public DateTime? CommentDeletedAt { get; set; }
    }
}

Filminurk/Models/UserComments/UserCommentsIndexViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Filminurk.Models.UserComments
{
    public class UserCommentsIndexViewModel
    {
        [Key]
        public Guid CommentID { get; set; }
        public string? CommentUserID { get; set; }
        public string? CommentBody { get; set; }
        public int? CommentScore { get; set; }
        public int? IsHelpful { get; set; }
        public int IsHarmful { get; set; }
        public DateTime CommentCreatedAt { get; set; }
        public DateTime CommentModifiedAt { get; set; }
        public DateTime? CommentDeletedAt { get; set; }
    }
}

Filminurk/Controllers/UserCommentsController.cs
using Filminurk.ApplicationServices.Services;
using Filminurk.Core.Dto;
using Filminurk.Core.ServiceInterface1;
using Filminurk.Data;
using Filminurk.Models.UserComments;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class UserCommentsController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly UserCommentServices _userCommentServices;
        public UserCommentsController(FilminurkTARpe24Context context, 
            IUserCommentServices userCommentServices)
        {
            _context = context;
            _userCommentServices= (UserCommentServices?)userCommentServices;
        }
        public IActionResult Index()
        {
            var result = _context.UserComments
                .Select(c => new UserCommentsIndexViewModel
                {
                   CommentID = c.CommentID,
                   CommentBody = c.CommentBody,
                   IsHarmful = c.IsHarmful,
                   CommentCreatedAt= c.CommentCreatedAt,
                }
                );
               return View(result);
        }
        [HttpGet]
        public IActionResult NewComment()
        {
            //todo: erista kas tegemist on admin või tava kasutajaga
            UserCommentsCreateViewModel newcomment = new();
            return View(newcomment);
        }
        [HttpPost, ActionName("NewComment")]
        //ei tohi panna allowanonymous
        public async Task<IActionResult> NewCommentPost(UserCommentsCreateViewModel newcommentVM)
        {
            //todo: newcommenti manuaalne seadmine, asenda pärast kasutaja id-ga
            //newcommentVM.CommentUserID = "00000000-0000-0000-000000000001";
            Console.WriteLine(newcommentVM.CommentUserID);
            if (ModelState.IsValid)
            {
                var dto = new UserCommentsDTO()
                { };
                dto.CommentID = newcommentVM.CommentID;
                dto.CommentBody = newcommentVM.CommentBody;
                dto.CommentUserID = newcommentVM.CommentUserID;
                dto.CommentScore = (int)newcommentVM.CommentScore;
                dto.CommentCreatedAt = newcommentVM.CommentCreatedAt;
                dto.CommentModifiedAt = newcommentVM.CommentModifiedAt;
                dto.CommentDeletedAt = newcommentVM.CommentDeletedAt;
                dto.IsHarmful = newcommentVM.IsHarmful;
                dto.IsHelpful = newcommentVM.IsHelpful;
                
                var result = await _userCommentServices.NewComment(dto);
                if (result == null)
                {
                    return NotFound();
                }
                //todo : erista ära kas tegu on admini või kasutajaga, admin
                //tagastub admin-comment-index, kasutaja aga vastava filmi juurde
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }
        [HttpGet]
        public async Task<IActionResult> DetailsAdmin(Guid id)
        {
            var requestedComment= await _userCommentServices.DetailAsync(id);
           
            if (requestedComment == null) {  return NotFound(); }
          
            var commentVM = new UserCommentsIndexViewModel();
            commentVM.CommentID = requestedComment.CommentID;
            commentVM.CommentBody = requestedComment.CommentBody;
            commentVM.CommentUserID = requestedComment.CommentUserID;
            commentVM.CommentScore = requestedComment.CommentScore;
            commentVM.CommentCreatedAt = requestedComment.CommentCreatedAt;
            commentVM.CommentModifiedAt= (DateTime)requestedComment.CommentModifiedAt;
            commentVM.CommentDeletedAt= requestedComment.CommentDeletedAt;

            return View(commentVM);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteAdmin(Guid id)
        {
            var deleteEntry = await _userCommentServices.DetailAsync(id);
            if (deleteEntry == null) { return NotFound(); }
            var commentVM = new UserCommentsIndexViewModel();
            commentVM.CommentUserID= deleteEntry.CommentUserID;
            commentVM.CommentID= deleteEntry.CommentID;
            commentVM.CommentBody= deleteEntry.CommentBody;
            commentVM.CommentScore= deleteEntry.CommentScore;
            commentVM.CommentCreatedAt= deleteEntry.CommentCreatedAt;
            commentVM.CommentDeletedAt = deleteEntry.CommentDeletedAt;
            commentVM.CommentModifiedAt= (DateTime)deleteEntry.CommentModifiedAt;
            return View("DeleteAdmin", commentVM);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAdminPost(Guid id)
        {
            var deleteThisComment=await _userCommentServices.Delete(id);
            if (deleteThisComment == null) {return NotFound(); }
            return RedirectToAction("Index");
           
        }

    }
}

Filminurk/Views/UserComments/DeleteAdmin.cshtml
@model Filminurk.Models.UserComments.UserCommentsIndexViewModel

<h1>Vaata kommentaari</h1>
<div>
	<h4>Info:</h4>
	<hr />
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentID" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentID)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentUserID" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentUserID)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentBody" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentBody)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentScore" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentScore)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="IsHelpful" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.IsHelpful)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="IsHarmful" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.IsHarmful)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentCreatedAt" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentCreatedAt)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentModifiedAt" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentModifiedAt)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentDeletedAt" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentDeletedAt)
		</div>
	</dl>
	<hr />
	<form asp-action="DeleteAdmin" method="post">
		<a asp-action="Index" asp-controller="UserComments" class="btn btn-primary">Tagasi</a>
		<input type="hidden" asp-for="CommentID" />
		<input type="submit" value="Kustuta" asp-controller="UserComments" asp-action="DeleteAdminPost" asp-route-id="@Model.CommentID" class="btn btn-danger" />
	</form>
		
		
</div>

Filminurk/Views/UserComments/DetailsAdmin.cshtml
@model Filminurk.Models.UserComments.UserCommentsIndexViewModel

<h1>Vaata kommentaari</h1>
<div>
	<h4>Info:</h4>
	<hr />
    <dl class="row">
		<div class="form-group row">
			<label asp-for="CommentID" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentID)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentUserID" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentUserID)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentBody" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentBody)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentScore" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentScore)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="IsHelpful" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.IsHelpful)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="IsHarmful" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.IsHarmful)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentCreatedAt" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentCreatedAt)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentModifiedAt" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentModifiedAt)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CommentDeletedAt" class="col-sm 2 col-form-label"></label>
			@Html.DisplayFor(model => model.CommentDeletedAt)
		</div>
	</dl>
	<hr />
	<a asp-action="Index" asp-controller="UserComments" class="btn btn-primary">Tagasi</a>
</div>

Filminurk/Views/UserComments/Index.cshtml
@model IEnumerable<Filminurk.Models.UserComments.UserCommentsIndexViewModel>

@{
	int rownumber = 1;
}
<div>
	<a asp-action="NewComment" asp-controller="userComments" type="submit" class="btn btn-primary">Make new comment</a>
</div>
<div class="h1">
	Kasutajate arvustused:
</div>
<div>
	<form method="get">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">JKN</th>
					<th scope="col">CommentID</th>
					<th scope="col">CommentBody</th>
					<th scope="col">IsHarmful</th>
					<th scope="col">CommentCreatedAt</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var comment in Model)
				{
					<tr>
						<td>@rownumber</td>
						<td>@comment.CommentID</td>
						<td>@comment.CommentBody</td>
						<td>@comment.IsHarmful</td>
						<td>@comment.CommentCreatedAt</td>
						<td>
							<a asp-action="DetailsAdmin" asp-controller="UserComments" 
							asp-route-id="@comment.CommentID" class="btn btn-primary">Details</a>
							<a asp-action="DeleteAdmin" asp-controller="UserComments"
							asp-route-id="@comment.CommentID" class="btn btn-primary">Delete</a>
						</td>

					</tr>
					rownumber += 1;
				}

			</tbody>
		</table>
	</form>
</div>

Filminurk/Views/UserComments/NewComment.cshtml
@model Filminurk.Models.UserComments.UserCommentsCreateViewModel
<h1>Add New Comment</h1>
<div>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="CommentID" type="hidden" />
		<input asp-for="CommentCreatedAt" type="hidden" />
		<input asp-for="CommentModifiedAt" type="hidden" />
		<input asp-for="CommentUserID" type="hidden" />

		<div>
			<label asp-for="CommentBody"class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="CommentBody" />
			</div>
		</div>

		<div>
			<label asp-for="CommentScore" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="CommentScore" />
			</div>
		</div>

		<input asp-action="NewComment" asp-controller="UserComments" type="submit" 
		class="btn btn-success" value="Post Comment"/>
	</form>
</div>